import { Router } from 'express';
import multer from 'multer';
import { Prisma } from '@prisma/client';
import { requireAuth } from '../middleware/auth';
import { prisma } from '../prismaClient';
import { parseLinkedInAnalyticsXlsx, LinkedInAnalyticsParseError } from '../services/linkedinAnalyticsParser';
import { parseLinkedInProfilePdf } from '../services/linkedinProfileParser';
import { calculateLinkedInMetrics } from '../services/linkedinAnalyticsMetrics';
import { buildAnalysisContext, enrichTopPosts, generateAnalyticsInsights, jsonValue } from '../services/linkedinContentAnalyticsService';

const router=Router(); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}});
const include={dailyMetrics:{orderBy:{date:'asc' as const}},postMetrics:{orderBy:{impressions:'desc' as const}},demographics:true,insights:{orderBy:{createdAt:'asc' as const}}};
const friendly=(e:unknown)=>e instanceof LinkedInAnalyticsParseError?e.message:e instanceof multer.MulterError?'The file is too large. Maximum size is 15 MB.':'Analytics processing failed. Please verify the LinkedIn export and try again.';

router.get('/',requireAuth,async(req,res)=>{const reports=await prisma.linkedInAnalyticsImport.findMany({where:{userId:req.userId!},orderBy:{periodEnd:'desc'},select:{id:true,periodStart:true,periodEnd:true,status:true,impressions:true,membersReached:true,engagementCount:true,followerCount:true,createdAt:true}});res.json(reports)});
router.get('/profile',requireAuth,async(req,res)=>res.json(await prisma.linkedInProfileSnapshot.findFirst({where:{userId:req.userId!},orderBy:{createdAt:'desc'}})));
router.post('/profile',requireAuth,upload.single('profile'),async(req,res)=>{if(!req.file||req.file.mimetype!=='application/pdf')return res.status(400).json({message:'Please upload a PDF LinkedIn profile export.'});try{const p=await parseLinkedInProfilePdf(req.file.buffer);const saved=await prisma.linkedInProfileSnapshot.create({data:{userId:req.userId!,name:p.name,headline:p.headline,location:p.location,summary:p.summary,skills:p.skills,experience:p.experience,education:p.education,linkedinUrl:p.linkedinUrl}});res.status(201).json(saved)}catch{res.status(422).json({message:'The profile PDF could not be parsed. Analytics XLSX imports can still continue.'})}});
router.post('/import',requireAuth,upload.single('analytics'),async(req,res)=>{if(!req.file||!(/spreadsheetml/.test(req.file.mimetype)||/\.xlsx$/i.test(req.file.originalname)))return res.status(400).json({message:'Please upload a LinkedIn Analytics XLSX file.'});try{const normalized=parseLinkedInAnalyticsXlsx(req.file.buffer);const posts=await enrichTopPosts(req.userId!,normalized);const metrics=calculateLinkedInMetrics(normalized);const existing=await prisma.linkedInAnalyticsImport.findFirst({where:{userId:req.userId!,periodStart:new Date(normalized.period.start),periodEnd:new Date(normalized.period.end)}});if(existing)return res.status(409).json({message:'You already imported this reporting period.',reportId:existing.id});
 const created=await prisma.linkedInAnalyticsImport.create({data:{userId:req.userId!,periodStart:new Date(normalized.period.start),periodEnd:new Date(normalized.period.end),status:'ANALYZING',impressions:metrics.totalImpressions,membersReached:metrics.membersReached,engagementCount:metrics.totalEngagements,followerCount:metrics.followerCount,normalizedData:jsonValue(normalized),deterministicData:jsonValue({...metrics,contentPerformance:{}}),dailyMetrics:{create:normalized.engagementByDay.map(d=>({date:new Date(d.date),impressions:d.impressions,engagements:d.engagements,newFollowers:d.newFollowers}))},postMetrics:{create:posts.map(p=>({linkedinPostUrl:p.url,publishedAt:p.publishedAt?new Date(p.publishedAt):undefined,impressions:p.impressions,engagements:p.engagements,engagementRate:p.engagementRate,matchedPostId:p.matchedPostId,enrichment:p.enrichment?jsonValue(p.enrichment):undefined}))},demographics:{create:Object.entries(normalized.demographics).flatMap(([type,values])=>values.map(v=>({type,label:v.label,value:v.value})))}}});
 try{const context=await buildAnalysisContext(req.userId!,normalized,posts);const insights=await generateAnalyticsInsights(req.userId!,context);await prisma.linkedInAnalyticsImport.update({where:{id:created.id},data:{status:'READY',deterministicData:jsonValue({...metrics,contentPerformance:context.contentPerformance}),insights:{create:insights.map((i:any)=>({type:i.type,importance:i.importance,title:i.title,finding:i.finding,recommendation:i.recommendation,nextMove:i.nextMove,evidence:jsonValue(i.evidence),confidence:i.confidence}))}}});}catch(e){await prisma.linkedInAnalyticsImport.update({where:{id:created.id},data:{status:'READY',analysisError:e instanceof Error?e.message:'AI analysis failed'}});}
 res.status(201).json(await prisma.linkedInAnalyticsImport.findUnique({where:{id:created.id},include}));}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')return res.status(409).json({message:'You already imported this reporting period.'});res.status(422).json({message:friendly(e)})}});
router.get('/:id',requireAuth,async(req,res)=>{const report=await prisma.linkedInAnalyticsImport.findFirst({where:{id:req.params.id,userId:req.userId!},include});if(!report)return res.status(404).json({message:'Analytics report not found.'});const previous=await prisma.linkedInAnalyticsImport.findFirst({where:{userId:req.userId!,periodEnd:{lt:report.periodStart}},orderBy:{periodEnd:'desc'}});res.json({...report,previousPeriod:previous?{id:previous.id,impressions:previous.impressions,membersReached:previous.membersReached,engagementCount:previous.engagementCount,followerCount:previous.followerCount}:null})});
router.post('/:id/analyze',requireAuth,async(req,res)=>{const report=await prisma.linkedInAnalyticsImport.findFirst({where:{id:req.params.id,userId:req.userId!}});if(!report)return res.status(404).json({message:'Analytics report not found.'});try{const normalized=report.normalizedData as any;const posts=await enrichTopPosts(req.userId!,normalized);const context=await buildAnalysisContext(req.userId!,normalized,posts);const insights=await generateAnalyticsInsights(req.userId!,context);await prisma.$transaction([prisma.linkedInAnalyticsInsight.deleteMany({where:{importId:report.id}}),prisma.linkedInAnalyticsImport.update({where:{id:report.id},data:{analysisError:null,status:'READY',insights:{create:insights.map((i:any)=>({type:i.type,importance:i.importance,title:i.title,finding:i.finding,recommendation:i.recommendation,nextMove:i.nextMove,evidence:jsonValue(i.evidence),confidence:i.confidence}))}}})]);res.json(await prisma.linkedInAnalyticsImport.findUnique({where:{id:report.id},include}))}catch(e){res.status(502).json({message:e instanceof Error?e.message:'AI analysis failed.'})}});
export default router;
